### ISSUE TITLE
undefined local variable or method `validation_group_class'

### ISSUE THREAD

**Issue by dwayne** [apotonick/trailblazer#126]
I decided to play with Trailblazer to get a feel for the API so I created a simple `app.rb` file to experiment with `Trailblazer::Operation`. Not too far into the experimentation and I'm having some trouble.

```rb
require 'trailblazer'

class Create < Trailblazer::Operation
  contract do
    property :body, validates: { presence: true }
  end

  def process(params)
  end
end
```

When I run it

```sh
$ bundle exec ruby app.rb
```

I get the following error:

```sh
/home/dwayne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reform-2.1.0/lib/reform/validation.rb:6:in `validation_groups': undefined local variable or method `validation_group_class' for #<Class:0x007f5800c6abd8> (NameError)
Did you mean?  validation_groups
	from /home/dwayne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reform-2.1.0/lib/reform/validation.rb:13:in `validation'
	from /home/dwayne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reform-2.1.0/lib/reform/validation.rb:19:in `validates'
	from /home/dwayne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reform-2.1.0/lib/reform/contract.rb:24:in `property'
	from /home/dwayne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/reform-2.1.0/lib/reform/form.rb:19:in `property'
	from app.rb:6:in `block in <class:Create>'
	from /home/dwayne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/trailblazer-1.1.1/lib/trailblazer/operation.rb:56:in `class_eval'
	from /home/dwayne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/trailblazer-1.1.1/lib/trailblazer/operation.rb:56:in `contract'
	from app.rb:5:in `<class:Create>'
	from app.rb:4:in `<main>'
```

I'm using gem version 1.1.1.

**Comment by apotonick** [comment]
It depends on what validation backend you want to use. I recommend for simplicity, use `gem "trailblazer-rails"`. It will set it automatically to ActiveModel.

**Comment by dwayne** [comment]
Thanks, but I don't plan to use it with Rails. So I'd rather understand why that error is occurring. Can you explain? I want to use it with Roda, Sequel and dry-validations.

**Comment by apotonick** [comment]
A good plan! :smile: You have to tell Reform what validation backend you're gonna use.

This will do the trick: https://github.com/apotonick/reform/blob/7bfa34cb4bef3da7b51886427ff3134559c612f0/test/test_helper.rb#L54

**Comment by dwayne** [comment]
Thanks, but unfortunately that didn't work for me either.

This is my `app.rb`:

```rb
require 'pry'
require 'trailblazer'

require 'reform/form/dry'
Reform::Contract.class_eval do
  feature Reform::Form::Dry
end

Reform::Form.class_eval do
  feature Reform::Form::Dry
end

class Create < Trailblazer::Operation
  contract do
    property :body, validates: { presence: true }
  end

  def process(params)
  end
end

binding.pry
```

And this is my `Gemfile`:

```rb
source 'https://rubygems.org/'

gem 'dry-validation'
gem 'pry'
gem 'trailblazer'
```

**Comment by apotonick** [comment]
`gem "reform", github: "apotonick/reform", branch: "2-2"` - I try to release that one next week when I'm back home!

**Comment by dwayne** [comment]
Thanks alot, that worked for me.

**Comment by apotonick** [comment]
:beers:
