### ISSUE TITLE
concept test helper not returning html

### ISSUE THREAD

**Issue by jasonelston** [apotonick/trailblazer#53]
I've been trying to test the concept helper as part of the cells piece of the Trailblazer book but I can't get the tests working. The page is rendering in a browser but the tests aren't passing. It looks like the `concept` testing helper isn't returning html.

With the following `cell_test.rb`:

```ruby
require 'test_helper'

##
class ThingCellTest < Cell::TestCase
  let(:rails) { Thing::Create[thing: { name: 'Rails' }] }
  let(:trb) { Thing::Create[thing: { name: 'Trailblazer' }] }

  # subject { concept('thing/cell', collection: [trb, rails], last: rails) }
  subject { concept('thing/cell', Thing.last) }

  it do
    # subject.must_have_selector '.columns .header a', text: 'Rails'
    subject.must_equal 'something'
  end
end
```

I get the following failure:
 
``` ruby
Failure:
ThingCellTest#test_0001_anonymous [/Users/jasonelston/dev/jasonelston/gemgem/test/concepts/thing/cell_test.rb:13]
Minitest::Assertion: --- expected
+++ actual
@@ -1 +1 @@
-"something"
+#<Thing::Cell:0xXXXXXX @parent_controller=nil, @model=nil, @options={}>
```

`subject` is being returned as a `Thing::Cell` object but shouldn't it be a HTML string?

Another concern is that the `@model` is empty.

I also tried testing a collection instead

```ruby
require 'test_helper'

##
class ThingCellTest < Cell::TestCase
  let(:rails) { Thing::Create[thing: { name: 'Rails' }] }
  let(:trb) { Thing::Create[thing: { name: 'Trailblazer' }] }

  subject { concept('thing/cell', collection: [trb, rails], last: rails) }
  # subject { concept('thing/cell', Thing.last) }

  it do
    # subject.must_have_selector '.columns .header a', text: 'Rails'
    subject.must_equal 'something'
  end
end
```

with the result of:

``` ruby
Failure:
ThingCellTest#test_0001_anonymous [/Users/jasonelston/dev/jasonelston/gemgem/test/concepts/thing/cell_test.rb:13]
Minitest::Assertion: --- expected
+++ actual
@@ -1 +1 @@
-"something"
+#<Thing::Cell:0xXXXXXX @parent_controller=nil, @model={:collection=>[#<Thing::Create:0xXXXXXX @valid=true, @raise_on_invalid=true, @model=#<Thing id: 93, name: "Trailblazer", description: nil, created_at: "2015-05-20 22:59:09", updated_at: "2015-05-20 22:59:09">, @contract=#<#<Class:0xXXXXXX>:0xXXXXXX @model=#<Thing id: 93, name: "Trailblazer", description: nil, created_at: "2015-05-20 22:59:09", updated_at: "2015-05-20 22:59:09">, @fields=#<Reform::Contract::Fields name="Trailblazer", description=nil>, @changed={"name"=>true}, @validation_context=nil, @errors=#<Reform::Contract::Errors:0xXXXXXX @base=#<#<Class:0xXXXXXX>:0xXXXXXX ...>, @messages={}>>>, #<Thing::Create:0xXXXXXX @valid=true, @raise_on_invalid=true, @model=#<Thing id: 94, name: "Rails", description: nil, created_at: "2015-05-20 22:59:09", updated_at: "2015-05-20 22:59:09">, @contract=#<#<Class:0xXXXXXX>:0xXXXXXX @model=#<Thing id: 94, name: "Rails", description: nil, created_at: "2015-05-20 22:59:09", updated_at: "2015-05-20 22:59:09">, @fields=#<Reform::Contract::Fields name="Rails", description=nil>, @changed={"name"=>true}, @validation_context=nil, @errors=#<Reform::Contract::Errors:0xXXXXXX @base=#<#<Class:0xXXXXXX>:0xXXXXXX ...>, @messages={}>>>], :last=>#<Thing::Create:0xXXXXXX @valid=true, @raise_on_invalid=true, @model=#<Thing id: 94, name: "Rails", description: nil, created_at: "2015-05-20 22:59:09", updated_at: "2015-05-20 22:59:09">, @contract=#<#<Class:0xXXXXXX>:0xXXXXXX @model=#<Thing id: 94, name: "Rails", description: nil, created_at: "2015-05-20 22:59:09", updated_at: "2015-05-20 22:59:09">, @fields=#<Reform::Contract::Fields name="Rails", description=nil>, @changed={"name"=>true}, @validation_context=nil, @errors=#<Reform::Contract::Errors:0xXXXXXX @base=#<#<Class:0xXXXXXX>:0xXXXXXX ...>, @messages={}>>>}, @options={}>
```

This is obviously assigning the model with a collection but still not returning a HTML string.

Am I doing something wrong?

**Comment by apotonick** [comment]
I know, I know, that's a bit of a pain right now, since Cells 4 is not out, yet.

Here's how I get the assertions into the HTML: https://github.com/apotonick/gemgem-trbrb/blob/master/test/concepts/comment/cell_test.rb#L22

**Comment by jasonelston** [comment]
Thanks you, got it working.

For the benefits of anyone else looking, I also needed to make sure that I was explicitly passing the model.

``` ruby
html = concept('thing/cell', rails.model).(:show)
```

and specifying to controller at the top of `ThingCellTest` to provide the controller reference to the `concept` helper.

``` ruby
class ThingCellTest < Cell::TestCase
  controller ThingsController
  ...
end
```

**Comment by apotonick** [comment]
Cool! I might spend a few hours this weekend on Cells and ship the test library code.

**Comment by jasonelston** [comment]
Great!

Unfortunately I spoke too soon though :smile:

The above works for single cells, I'm still getting a problem with cell collections with render trying to access the `name` attrubute for a `Hash`. Any ideas? A clumsy attempt at ensuring `.model` references were passed to the collection failed.

``` ruby
Error:
ThingCellTest#test_0001_anonymous:
NoMethodError: undefined method `name' for #<Hash:0x007fad32adc668>
    app/concepts/thing/cell.rb:17:in `name_link'
    app/concepts/thing/views/show.haml:4:in `block in singleton class'
    app/concepts/thing/views/show.haml:-8:in `instance_eval'
    app/concepts/thing/views/show.haml:-8:in `singleton class'
    app/concepts/thing/views/show.haml:-10:in `__tilt_70190910276100'
    app/concepts/thing/cell.rb:11:in `show'
    test/concepts/thing/cell_test.rb:11:in `block in <class:ThingCellTest>'
```

**Comment by apotonick** [comment]
Please paste the test and the cell.

**Comment by jasonelston** [comment]
The test

``` ruby
require 'test_helper'

##
class ThingCellTest < Cell::TestCase
  controller ThingsController

  let(:rails) { Thing::Create[thing: { name: 'Rails' }] }
  let(:trb) { Thing::Create[thing: { name: 'Trailblazer' }] }

  it do
    html = concept('thing/cell', collection: [trb, rails], last: rails).(:show)
    # html = concept('thing/cell', rails.model).(:show)
    html = Capybara.string(html)

    html.must_have_selector '.columns .header a', text: 'Rails'
    html.must_have_selector '.columns .header a', text: 'Trailblazer'
  end
end
```

The cell

``` ruby
##
class Thing::Cell < Cell::Concept
  include ActionView::Helpers::DateHelper
  include Rails::Timeago::Helper

  property :name
  property :created_at


  def show
    render
  end

  private

  def name_link
    link_to model.name, thing_path(model)
  end

  def created_at
    timeago_tag(super)
  end

  def classes
    classes = ['large-3', 'columns']
    classes << 'end' if options[:last] == model
    classes
  end

  # class Grid < Cell:Concept
  #   def show
  #     things = Thing.latest
  #     concept('thing/cell', collection: things, last: things.last)
  #   end
  # end
end
```

And `index.html.haml`

``` ruby
%h3
  Welcome to Gemgem!

.row
  - things = Thing.latest
  = concept("thing/cell", collection: things, last: things.last)
  -# = concept("thing/cell", Thing.last)
```

**Comment by apotonick** [comment]
The `.(:show)` is wrong when rendering the collection, that mustn't be there!

**Comment by jasonelston** [comment]
OK, got it. Sorry, feels like I'm leading you down a rabbit hole.

It now looks like there's expectations around what methods are available as a cell collection

``` ruby
Error:
ThingCellTest#test_0001_anonymous:
NoMethodError: undefined method `css' for #<Thing::Cell:0x007fbc1229c2c0>
    test/concepts/thing/cell_test.rb:15:in `block in <class:ThingCellTest>'
```

`cell_test.rb` is now

``` ruby
require 'test_helper'

##
class ThingCellTest < Cell::TestCase
  controller ThingsController

  let(:rails) { Thing::Create[thing: { name: 'Rails' }] }
  let(:trb) { Thing::Create[thing: { name: 'Trailblazer' }] }

  it do
    html = concept('thing/cell', collection: [trb, rails], last: rails)
    # html = concept('thing/cell', rails.model).(:show)
    html = Capybara.string(html)

    html.must_have_selector '.columns .header a', text: 'Rails'
    html.must_have_selector '.columns .header a', text: 'Trailblazer'
  end
end
```

**Comment by apotonick** [comment]
Come join the #trailblazer channel on Freenode, IRC, please.

**Comment by apotonick** [comment]
@jasonelston I added Capybara support to `Cell::Testing`, it's still experimental but should do the trick. I tested it in gemgem, and it worked (after removing the manual `html = Capybara.string(html)`, of course).

Can you test and tell me how far you got?

**Comment by apotonick** [comment]
@jasonelston I added docs here: http://trailblazerb.org/gems/cells/testing.html

**Comment by apotonick** [comment]
And collections are working now, too. Please use Cells beta2 until I release a new version. Thanks!

**Comment by jasonelston** [comment]
Thank for taking the time @apotonick!

Could you please clarify how to test a collection now taking into account a namespaced concept?

from [cells/test/test_case_test.rb](https://github.com/apotonick/cells/blob/master/test/test_case_test.rb)

``` ruby
it { cell("test_case_test/song", collection: [song, song]).must_equal "Give It All!Give It All!" }
```

Will grab `SongCell`


``` ruby 
subject { concept("test_case_test/song/cell", song) }
```

will grab `Song::Cell`

Must a collection always be rendered in testing through the `cell` helper? If so, how do you grab `Song::Cell` from the `cell` helper?

**Comment by apotonick** [comment]
It's super simple.

 ```ruby
cell("namespace/that/makes/you/happy")
#=> Namespace::That::Makes::You::HappyCell
```

And.

 ```ruby
concept("namespace/that/makes/you/happy/cell")
#=> Namespace::That::Makes::You::Happy::Cell
```

It doesn't matter whether or not you're referencing a collection. The name gets resolved to a constant and then the collection is rendered using that cell.
